// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Js_json = require("bs-platform/lib/js/js_json.js");

((require('isomorphic-fetch')));

var api = "https://api.github.com/emojis";

fetch(api).then((function (prim) {
          return prim.json();
        })).then((function (json) {
        return Promise.resolve((console.log(Js_json.decodeObject(json)), /* () */0));
      }));

exports.api = api;
/*  Not a pure module */
